worker_processes auto;
pid /tmp/nginx.pid;

error_log /var/log/nginx/error.log;
events {
    worker_connections 1024;
}

http {
    client_body_temp_path /tmp/nginx_body;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    # Performance optimizations
    sendfile        on;
    keepalive_timeout 65;
    gzip on;

    # Define your server block
    server {
        listen 8000 default_server;
        server_name _;

        root /var/www/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param  HTTPS on;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        access_log /var/log/nginx/access.log;
    }
}
