[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid
nodaemon=true
user=www-data

[program:php-fpm]
user=www-data
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
stopsignal=TERM
stderr_logfile=/var/log/php-fpm/php-fpm.err.log
stdout_logfile=/var/log/php-fpm/php-fpm.out.log

[program:nginx]
user=www-data
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stopsignal=TERM
stderr_logfile=/var/log/nginx/nginx.err.log
stdout_logfile=/var/log/nginx/nginx.out.log
